name: Deploy Portfolio to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ AKIARTFLEESQXCDA565F }}
          aws-secret-access-key: ${{ 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 }}
          aws-region: us-east-2

      - uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          SOURCE_DIR: "./"
          AWS_S3_BUCKET: "lanportfolio"
